### PR TITLE
add notebook to classify poker card symbols from event-based camera recordings

### PR DESCRIPTION
**Pull request by biphasic**
This is my first attempt at playing with norse. I am using an event-based dataset called POKER-DVS, which records poker cards being flipped in front of an event-based camera. 
Because one recording has about 4k time steps and I'm currently converting to dense representations, the training is very slow (25 mins for 5 epochs on my GPU). I also didn't optimize the time constants which would probably provide a better result than just ~90% classification accuracy. 

Nevertheless the goal is to show that event-based datasets exist and that they can easily be used in conjunction with SNNs.

### CODE REVIEW

**Comment by cpehle** [comment]
This is a great start! The performance will hopefully improve once we fully support sparsity and event driven integration. This is a great motivation to look into that. I got an error locally because ```tonic.utils.pad_tensors``` could not be found, I suspect this is because the latest released version does not contain it yet. I could successfully execute the notebook using the main branch version of tonic. Otherwise I would be happy to merge this.

**Comment by biphasic** [comment]
oh sorry about that, that was my bad! I pushed the latest version to pypi.

**Review by cpehle — APPROVED** [review]
Thanks!

**Comment by Jegp** [comment]
Excellent work @biphasic :)

**Pull request merged**
